// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gasfvwnmbdjtpbgcltvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhc2Z2d25tYmRqdHBiZ2NsdHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODM2ODYsImV4cCI6MjA3MzE1OTY4Nn0.2JLvHNm8gJm-7PZq4OrBMiMENdv5ExNegISweNJMHgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});